### ISSUE TITLE
����ȫ��rm���������Ҫ���� | 骏马金龙

### ISSUE THREAD

**Issue by malongshuai** [malongshuai/malongshuai.github.io#301]
https://www.junmajinlong.com/shell/sort_trans/ 

 Linux����ϵ�����´��Shellϵ�����´��  sort���������ֲ�(info sort����)˵����  (1).���ֲ�ֻ��ѡ��info sort�����õ���Ϣ���з��룬��Ҫ�鿴�������������ݣ�������info sort�� (2).�����У���������ʹ����”ע”�ģ�Ϊ�������ӣ���ԭ�����ݣ

**Comment by vavikast** [comment]
我看到这边文章是乱码，你们看显示异常吗

**Comment by malongshuai** [comment]
> 我看到这边文章是乱码，你们看显示异常吗

不瞒你说，我自己看的也是乱码，但是我不知道是什么问题导致的。

**Comment by malongshuai** [comment]
> 我看到这边文章是乱码，你们看显示异常吗

我无论用什么编辑器打开看都是UTF8编码，但是用notepad++打开，就发现是GBK编码，而且改不动编码。

**Comment by malongshuai** [comment]
> 我看到这边文章是乱码，你们看显示异常吗

已经修改好了，现在不乱码了

**Comment by malongshuai** [comment]
新开评论
